version: '3.8'

services:
  app:
    build: .
    container_name: apec-job-manager
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/apec_job_manager
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
      - ./exports:/app/exports
      - ./screenshots:/app/screenshots

  db:
    image: postgres:14-alpine
    container_name: apec-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=apec_job_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
